FROM jenkins/jenkins:lts

USER root

RUN apt-get update \
 && apt-get install -y docker.io docker-compose \
 && groupmod -g 984 docker \
 && usermod -aG docker jenkins \
 && rm -rf /var/lib/apt/lists/*

USER jenkins
