services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_PASSWORD: gds
      MYSQL_USER: gds
      MYSQL_ROOT_PASSWORD: gds
      MYSQL_DATABASE: tws_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - twotier
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pgds"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  flaskapp:
    build: .
    container_name: flaskapp
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: gds
      MYSQL_PASSWORD: gds
      MYSQL_DB: tws_db
    networks:
      - twotier
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
volumes:
  mysql_data:
    name: mysql_data
    external: true

networks:
  twotier:
